# Generated by Django 3.0.7 on 2020-08-07 04:32

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('isGeneral', models.BooleanField(default=False)),
                ('isSubCategory', models.BooleanField(default=False, null=True)),
                ('parentCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_code', models.IntegerField(default=game.models.add_one, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option', models.CharField(max_length=100000, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreaks',
            fields=[
                ('email_address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('streaks', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_played', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('category', models.ManyToManyField(to='game.Category')),
                ('game_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100000)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('difficult', 'difficult'), ('medium', 'medium')], default='easy', max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correct', to='game.Options')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category')),
                ('options', models.ManyToManyField(to='game.Options')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
