# Generated by Django 3.0.7 on 2020-08-01 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isGeneral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isSubCategory',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Category'),
        ),
        migrations.AddField(
            model_name='usergames',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.IntegerField(default=game.models.add_one, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
