# Generated by Django 3.0.7 on 2020-07-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20200721_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.IntegerField(default=game.models.add_one, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correct', to='game.Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Category'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='game_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Game'),
        ),
    ]
