# Generated by Django 3.0.7 on 2020-08-01 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200801_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergames',
            name='game_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
