# Generated by Django 3.0.7 on 2020-08-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200816_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpauth',
            name='user',
        ),
    ]
