# Generated by Django 3.0.7 on 2020-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200807_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='questions',
            field=models.ManyToManyField(null=True, to='game.Question'),
        ),
    ]
