# Generated by Django 3.0.7 on 2020-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_usergames_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergames',
            name='questions',
        ),
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.ManyToManyField(null=True, to='game.Question'),
        ),
    ]
